/**
 * TypeScript Type Definitions for Receipt Generation API
 * 
 * This file can be shared between frontend and backend teams to ensure
 * type consistency across the entire receipt generation flow.
 * 
 * @version 1.0.0
 * @date 2025-12-11
 */

// ============================================================================
// Request Types
// ============================================================================

/**
 * Payment method options
 */
export type PaymentMethod = 'cash' | 'card' | 'online' | 'qr';

/**
 * Receipt format options
 */
export type ReceiptFormat = 'pdf' | 'html' | 'thermal';

/**
 * Transaction metadata
 */
export interface TransactionMetadata {
  /** Auto-generated by backend if not provided */
  transactionId?: string;
  /** ISO 8601 format timestamp */
  timestamp: string;
  /** Store/Location identifier */
  storeId?: string;
  /** POS terminal identifier */
  posTerminalId?: string;
  /** Employee who processed the sale */
  employeeId?: string;
  /** Employee name */
  employeeName?: string;
}

/**
 * Customer information
 */
export interface CustomerInfo {
  /** Customer full name */
  name?: string;
  /** Customer phone number */
  phone?: string;
  /** Customer email address */
  email?: string;
  /** Customer address */
  address?: string;
  /** Order notes/preferences */
  notes?: string;
  /** Customer ID if registered */
  customerId?: string;
}

/**
 * Single line item in the receipt
 */
export interface ReceiptItem {
  /** Product ID (if available) */
  id?: string;
  /** Product name (required) */
  name: string;
  /** Quantity purchased (required, must be > 0) */
  qty: number;
  /** Unit price (required, must be >= 0) */
  product_price: number;
  /** Tax percentage for this item */
  tax_percentage?: number;
  /** Calculated tax amount for this item */
  tax_amount?: number;
  /** Item-level discount (if any) */
  discount?: number;
  /** Subtotal: qty × product_price */
  subtotal: number;
  /** Total: subtotal + tax_amount - discount */
  total: number;
  /** Product barcode */
  barcode?: string;
  /** Product SKU */
  sku?: string;
  /** Product category */
  category?: string;
  /** Product image URL */
  imageUrl?: string;
}

/**
 * Discount information
 */
export interface DiscountInfo {
  /** Discount amount applied */
  amount: number;
  /** Whether discount is percentage-based */
  isPercentage: boolean;
  /** If percentage, the percentage value */
  percentage?: number;
}

/**
 * Payment details
 */
export interface PaymentDetails {
  /** Payment method selected */
  method: PaymentMethod;
  /** Subtotal before tax and discount */
  subtotal: number;
  /** Total tax amount */
  tax: number;
  /** Discount information */
  discount: DiscountInfo;
  /** Final total amount */
  total: number;
  /** Total number of items */
  totalItems: number;
  /** Amount tendered (for cash payments) */
  tendered?: number;
  /** Change given (for cash payments) */
  change?: number;
  /** Last 4 digits of card (for card payments) */
  cardLast4?: string;
  /** Card brand (Visa, Mastercard, etc.) */
  cardBrand?: string;
  /** Payment gateway transaction reference */
  transactionReference?: string;
}

/**
 * Receipt preferences
 */
export interface ReceiptPreferences {
  /** Whether to email the receipt */
  emailReceipt: boolean;
  /** Whether to print physical receipt */
  printReceipt?: boolean;
  /** Receipt format */
  format?: ReceiptFormat;
}

/**
 * Complete receipt generation request
 */
export interface ReceiptGenerationRequest {
  /** Transaction metadata */
  transaction: TransactionMetadata;
  /** Customer information (null if no customer) */
  customer: CustomerInfo | null;
  /** Line items array */
  items: ReceiptItem[];
  /** Payment details */
  payment: PaymentDetails;
  /** Receipt preferences */
  receipt: ReceiptPreferences;
}

// ============================================================================
// Response Types
// ============================================================================

/**
 * Validation error detail
 */
export interface ValidationError {
  /** Field that failed validation */
  field: string;
  /** Error message */
  message: string;
}

/**
 * Receipt generation response data
 */
export interface ReceiptData {
  /** Unique receipt identifier */
  receiptId: string;
  /** Human-readable receipt number (e.g., "RCP-2025-001234") */
  receiptNumber: string;
  /** Transaction identifier */
  transactionId: string;
  /** URL to download/view receipt (if stored) */
  receiptUrl?: string;
  /** Whether email was sent successfully */
  emailSent?: boolean;
  /** Print job identifier (if print requested) */
  printJobId?: string;
  /** ISO 8601 timestamp of generation */
  generatedAt: string;
}

/**
 * Successful receipt generation response
 */
export interface ReceiptGenerationResponse {
  /** Success status */
  success: boolean;
  /** Response message */
  message: string;
  /** Receipt data */
  data?: ReceiptData;
  /** Validation errors (if any) */
  errors?: ValidationError[];
}

// ============================================================================
// Helper Types for Frontend State
// ============================================================================

/**
 * Ring-up item from Redux store (frontend state)
 */
export interface RingUpItem {
  id?: string;
  name: string;
  qty: number;
  product_price: number;
  tax_percentage?: number;
  barcode?: string;
  sku?: string;
  category?: string;
  imageUrl?: string;
  discount?: number;
}

/**
 * Customer form data from modal (frontend state)
 */
export interface CustomerFormData {
  name: string;
  phone: string;
  email: string;
  address: string;
  notes: string;
}

/**
 * Checkout data from payment modal (frontend state)
 */
export interface CheckoutData {
  tendered: number;
  change: number;
  emailReceipt: boolean;
  cardLast4?: string;
  cardBrand?: string;
  transactionReference?: string;
}

/**
 * Summary calculations (frontend state)
 */
export interface PaymentSummary {
  subtotal: number;
  tax: number;
  discount: number;
  total: number;
  totalItems: number;
  isPercentage: boolean;
  discountPercentage?: number;
}

/**
 * Transaction metadata options (frontend state)
 */
export interface TransactionMetadataOptions {
  storeId?: string;
  posTerminalId?: string;
  employeeId?: string;
  employeeName?: string;
}

// ============================================================================
// API Endpoint Constants
// ============================================================================

/**
 * API endpoints related to receipts
 */
export const RECEIPT_API_ENDPOINTS = {
  /** Generate a new receipt */
  GENERATE: '/api/receipts/generate',
  /** Get receipt by ID */
  GET_BY_ID: '/api/receipts/:receiptId',
  /** Get receipt by transaction ID */
  GET_BY_TRANSACTION: '/api/receipts/transaction/:transactionId',
  /** Resend receipt email */
  RESEND_EMAIL: '/api/receipts/:receiptId/resend-email',
  /** Reprint receipt */
  REPRINT: '/api/receipts/:receiptId/print',
} as const;

// ============================================================================
// Validation Constants
// ============================================================================

/**
 * Validation rules and constraints
 */
export const RECEIPT_VALIDATION_RULES = {
  /** Minimum items required */
  MIN_ITEMS: 1,
  /** Maximum items allowed in single transaction */
  MAX_ITEMS: 1000,
  /** Minimum total amount */
  MIN_TOTAL: 0.01,
  /** Maximum total amount */
  MAX_TOTAL: 999999.99,
  /** Email regex pattern */
  EMAIL_PATTERN: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  /** Phone pattern (basic) */
  PHONE_PATTERN: /^[+]?[(]?[0-9]{1,4}[)]?[-\s.]?[(]?[0-9]{1,4}[)]?[-\s.]?[0-9]{1,9}$/,
  /** Allowed payment methods */
  PAYMENT_METHODS: ['cash', 'card', 'online', 'qr'] as const,
  /** Allowed receipt formats */
  RECEIPT_FORMATS: ['pdf', 'html', 'thermal'] as const,
} as const;

// ============================================================================
// Type Guards
// ============================================================================

/**
 * Type guard to check if payment method is valid
 */
export function isValidPaymentMethod(method: string): method is PaymentMethod {
  return RECEIPT_VALIDATION_RULES.PAYMENT_METHODS.includes(method as PaymentMethod);
}

/**
 * Type guard to check if receipt format is valid
 */
export function isValidReceiptFormat(format: string): format is ReceiptFormat {
  return RECEIPT_VALIDATION_RULES.RECEIPT_FORMATS.includes(format as ReceiptFormat);
}

/**
 * Type guard to check if response is successful
 */
export function isSuccessfulResponse(
  response: ReceiptGenerationResponse
): response is ReceiptGenerationResponse & { success: true; data: ReceiptData } {
  return response.success === true && response.data !== undefined;
}

/**
 * Type guard to check if response has errors
 */
export function hasValidationErrors(
  response: ReceiptGenerationResponse
): response is ReceiptGenerationResponse & { success: false; errors: ValidationError[] } {
  return response.success === false && Array.isArray(response.errors) && response.errors.length > 0;
}

// ============================================================================
// Utility Types
// ============================================================================

/**
 * Make all properties of T optional recursively
 */
export type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P];
};

/**
 * Make specific properties required
 */
export type RequireFields<T, K extends keyof T> = T & Required<Pick<T, K>>;

/**
 * Omit specific properties from T
 */
export type OmitFields<T, K extends keyof T> = Omit<T, K>;

/**
 * Receipt item with all calculated fields required
 */
export type CalculatedReceiptItem = RequireFields<
  ReceiptItem,
  'subtotal' | 'total' | 'tax_amount'
>;

/**
 * Minimal receipt request (for testing/mocking)
 */
export type MinimalReceiptRequest = {
  transaction: Pick<TransactionMetadata, 'timestamp'>;
  customer: null;
  items: Array<Pick<ReceiptItem, 'name' | 'qty' | 'product_price' | 'subtotal' | 'total'>>;
  payment: Pick<PaymentDetails, 'method' | 'subtotal' | 'tax' | 'discount' | 'total' | 'totalItems'>;
  receipt: Pick<ReceiptPreferences, 'emailReceipt'>;
};

// ============================================================================
// Export all types
// ============================================================================

export type {
  ReceiptGenerationRequest as default,
};
